// AUTO-GENERATED by `npm run gen:bindings` — do not edit by hand.
// Source of truth: src-tauri/src/error.rs and src-tauri/src/core/**.

export type ProcId = string;

export type ProcKind = "pio" | "claude" | "installer" | "tool";

export type StdStream = "stdout" | "stderr";

export type LogLine = { stream: StdStream, text: string, tsMs: number, };

export type ProcSummary = { id: ProcId, label: string, kind: ProcKind, startedAtMs: number, pid: number | null, };

export type PermissionDenial = { tool: string, reason: string, };

export type AppError = { "code": "TOOL_MISSING", tool: string, installAction: boolean, } | { "code": "TOOL_TOO_OLD", tool: string, found: string, minimum: string, } | { "code": "CLAUDE_UNAUTHENTICATED" } | { "code": "CLAUDE_PERMISSION_DENIED", denials: Array<PermissionDenial>, } | { "code": "CLAUDE_INTERRUPTED", sessionId: string, } | { "code": "NETWORK_UNAVAILABLE", host: string, } | { "code": "PIO_COMMAND_FAILED", argv: Array<string>, exitCode: number, tail: string, } | { "code": "CLAUDE_PROCESS_FAILED", exitCode: number, tail: string, } | { "code": "BUILD_FAILED", defects: number, } | { "code": "PORT_BUSY", port: string, heldBy: string, } | { "code": "PORT_DISAPPEARED", port: string, } | { "code": "NOT_A_PIO_PROJECT", path: string, } | { "code": "INI_PARSE", path: string, line: number | null, message: string, } | { "code": "INI_CHANGED_ON_DISK", path: string, } | { "code": "WORKSPACE_UNTRUSTED", hooks: Array<string>, mcpServers: Array<string>, } | { "code": "SNAPSHOT_FAILED", message: string, } | { "code": "IO", message: string, };

export type ProbeResult = { "status": "ok", version: string, path: string | null, detail: string | null, } | { "status": "missing", installAvailable: boolean, } | { "status": "degraded", reason: string, remediation: Remediation | null, } | { "status": "error", detail: string, } | { "status": "probing" };

export type RemediationKind = "installClaude" | "installPio" | "authenticateClaude" | "installUdevRules" | "openUrl" | "showCommand";

export type Remediation = { kind: RemediationKind, label: string, commandPreview: Array<string> | null, url: string | null, };

export type DoctorReport = { claudeBinary: ProbeResult, claudeAuth: ProbeResult, claudeCapabilities: Array<string>, pioBinary: ProbeResult, pioCoreDir: ProbeResult, python: ProbeResult, networkRegistry: ProbeResult, serialPermissions: ProbeResult, git: ProbeResult, 
/**
 * RFC3339.
 */
probedAt: string, };

export type InstallEvent = { "type": "started", "data": { argv: Array<string>, } } | { "type": "line", "data": { stream: StdStream, text: string, } } | { "type": "progress", "data": { message: string, fraction: number | null, } } | { "type": "finished", "data": { success: boolean, exitCode: number, } };

export type InstallPlan = { 
/**
 * The canonical one-liner shown to the user before anything runs (FR-SETUP-3) — this
 * is display text, never executed as a shell string.
 */
commandPreview: string, sourceUrl: string, };

export type ToolchainTool = "claude" | "pio";

export type ToolchainSettings = { 
/**
 * `null` = auto-resolve (`core/toolchain::resolve`).
 */
claudePath: string | null, pioPath: string | null, pythonPath: string | null, autoProbeOnFocus: boolean, };

export type PermissionPolicySetting = "guarded" | "assisted" | "unrestricted";

export type ClaudeSettings = { permissionPolicy: PermissionPolicySetting, model: string, maxTurns: number | null, showThinking: boolean, showCostEstimate: boolean, };

export type PipelinePolicySetting = "safe" | "fastPath" | "watch";

export type PipelineSettings = { policy: PipelinePolicySetting, autoReattachMonitor: boolean, parallelJobs: number | null, stopGraceMs: number, };

export type MonitorSettings = { maxLines: number, maxBytes: number, timestamps: boolean, autoscroll: boolean, };

export type LogSettings = { maxLines: number, };

export type EditorSettings = { command: string | null, gotoLineArgTemplate: string, };

export type ThemeSetting = "system" | "light" | "dark";

export type AppearanceSettings = { theme: ThemeSetting, fontScale: number, monoFont: string | null, };

export type NetworkSettings = { registryTimeoutMs: number, boardCatalogueTtlHours: number, };

export type AdvancedSettings = { keepProcessLogs: boolean, 
/**
 * Reset to `false` on every app version change (`DATA-MODEL.md` §3 migration rule).
 */
allowUnrestrictedPolicy: boolean, };

export type GlobalSettings = { schemaVersion: number, 
/**
 * The app version that last wrote this file — compared at startup against the
 * running app's own version to drive the `apply_version_migration` reset. `None`
 * covers both a fresh install and a file written before this field existed; either
 * way, resetting is the safe default (`DATA-MODEL.md` §3).
 */
lastAppVersion: string | null, toolchain: ToolchainSettings, claude: ClaudeSettings, pipeline: PipelineSettings, monitor: MonitorSettings, logs: LogSettings, editor: EditorSettings, appearance: AppearanceSettings, network: NetworkSettings, advanced: AdvancedSettings, };

export type GlobalSettingsPatch = { toolchain: ToolchainSettings | null, claude: ClaudeSettings | null, pipeline: PipelineSettings | null, monitor: MonitorSettings | null, logs: LogSettings | null, editor: EditorSettings | null, appearance: AppearanceSettings | null, network: NetworkSettings | null, advanced: AdvancedSettings | null, };

export type Severity = "error" | "warning" | "note";

export type DefectSource = "compiler" | "linker" | "check";

export type Defect = { file: string, line: number, column: number | null, severity: Severity, message: string, source: DefectSource, raw: string, };

export type SizeUsage = { ramUsed: number, ramTotal: number, flashUsed: number, flashTotal: number, ramDelta: number | null, flashDelta: number | null, };

export type ProcEvent = { "type": "started", "data": { procId: ProcId, label: string, argv: Array<string>, } } | { "type": "lines", "data": { procId: ProcId, lines: Array<LogLine>, } } | { "type": "defect", "data": { procId: ProcId, defect: Defect, } } | { "type": "size", "data": { procId: ProcId, usage: SizeUsage, } } | { "type": "stage", "data": { procId: ProcId, stage: string, } } | { "type": "finished", "data": { procId: ProcId, success: boolean, exitCode: number, durationMs: number, } };

export type BoardSource = "registry" | "installed";

export type BoardBrief = { id: string, name: string, platform: string, mcu: string, fcpu: number, ram: number, rom: number, frameworks: Array<string>, vendor: string, url: string, connectivity: Array<string>, debugTools: Array<string>, };

export type CreateProjectRequest = { parentDir: string, name: string, boardId: string, framework: string, sampleCode: boolean, initGit: boolean, generateClaudeMd: boolean, 
/**
 * Repeatable `-O name=value` project options.
 */
extraOptions: Array<[string, string]>, };

export type ProjectEntry = { id: string, name: string, path: string, boardId: string | null, activeEnv: string | null, lastOpened: string | null, lastBuildOk: boolean | null, exists: boolean, trusted: boolean, };

export type CreatedBy = "vibe-hardware" | "opened";

export type StickyHwid = { vid: string, pid: string, serial: string | null, };

export type DeviceSettings = { preferredPort: string | null, stickyHwid: StickyHwid | null, };

export type ProjectClaudeSettings = { sessionId: string | null, permissionPolicy: PermissionPolicySetting | null, model: string | null, };

export type ProjectPipelineSettings = { policy: PipelinePolicySetting | null, };

export type ProjectSettings = { schemaVersion: number, 
/**
 * `WorkspaceId`, generated on first open/create and stable across moves — this is
 * what the registry reconciles on, not the path.
 */
id: string, name: string, activeEnv: string | null, device: DeviceSettings, claude: ProjectClaudeSettings, pipeline: ProjectPipelineSettings, trusted: boolean, 
/**
 * RFC3339.
 */
trustScanAt: string | null, createdBy: CreatedBy, 
/**
 * RFC3339.
 */
createdAt: string, };

export type TrustScan = { 
/**
 * Hook event names found in `.claude/settings.json`'s `hooks` object, e.g.
 * `"SessionStart"`, `"PreToolUse"`.
 */
hooks: Array<string>, 
/**
 * Server names from `.mcp.json`'s `mcpServers` object.
 */
mcpServers: Array<string>, 
/**
 * File stems under `.claude/agents/`.
 */
agents: Array<string>, };

export type SnapshotId = string;

export type ChangeStatus = "added" | "modified" | "deleted" | "renamed";

export type FileChange = { path: string, status: ChangeStatus, additions: number, deletions: number, 
/**
 * Drives the `FR-SAFE-4` warning banner: `true` when `path` isn't under `src/`,
 * `include/`, `lib/`, `test/`, `data/`, or exactly `platformio.ini`.
 */
outsideExpectedDirs: boolean, };

export type FileDiff = { path: string, before: string | null, after: string | null, };

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null;

export type TurnId = string;

export type SessionId = string;

export type PermissionPolicy = "guarded" | "assisted" | "unrestricted";

export type TurnRequest = { workspace: string, prompt: string, 
/**
 * Relative paths under `.vibe/attachments` (`FR-CHAT-9`, M8). Always empty in M3 —
 * no attachment UI yet.
 */
attachments: Array<string>, policy: PermissionPolicy | null, model: string | null, };

export type ChatEvent = { "type": "sessionReady", "data": { sessionId: SessionId, model: string, tools: Array<string>, capabilities: Array<string>, mcpErrors: Array<string>, pluginErrors: Array<string>, } } | { "type": "textDelta", "data": { turnId: TurnId, blockIndex: number, text: string, } } | { "type": "textBlock", "data": { turnId: TurnId, blockIndex: number, text: string, } } | { "type": "thinkingDelta", "data": { turnId: TurnId, blockIndex: number, text: string, } } | { "type": "toolCallStarted", "data": { turnId: TurnId, toolUseId: string, name: string, inputPreview: string, } } | { "type": "toolCallInputDelta", "data": { turnId: TurnId, toolUseId: string, partialJson: string, } } | { "type": "toolCallCompleted", "data": { turnId: TurnId, toolUseId: string, name: string, input: JsonValue, } } | { "type": "toolResult", "data": { turnId: TurnId, toolUseId: string, isError: boolean, summary: string, full: string | null, } } | { "type": "subagentMessage", "data": { turnId: TurnId, parentToolUseId: string, role: string, text: string, } } | { "type": "apiRetry", "data": { turnId: TurnId, attempt: number, maxRetries: number, retryDelayMs: number, error: string, errorStatus: number | null, } } | { "type": "permissionDenied", "data": { turnId: TurnId, tool: string, reason: string, } } | { "type": "compactBoundary", "data": { turnId: TurnId, } } | { "type": "result", "data": { turnId: TurnId, sessionId: SessionId, subtype: string, isError: boolean, numTurns: number, durationMs: number, durationApiMs: number, totalCostUsd: number | null, resultText: string | null, permissionDenials: Array<string>, } } | { "type": "changesComputed", "data": { turnId: TurnId, snapshot: SnapshotId, changes: Array<FileChange>, } } | { "type": "failed", "data": { turnId: TurnId, error: AppError, } };

export type TurnToolCall = { toolUseId: string, name: string, input: JsonValue, isError: boolean, };

export type TurnResultMeta = { subtype: string, isError: boolean, numTurns: number, durationMs: number, durationApiMs: number, totalCostUsd: number | null, permissionDenials: Array<string>, };

export type TurnRecord = { schemaVersion: number, turnId: string, sessionId: string, 
/**
 * RFC3339.
 */
startedAt: string, 
/**
 * RFC3339. `None` if the turn is still recorded as in-flight (shouldn't happen once
 * `append_turn` runs — every call site finalizes `endedAt` first).
 */
endedAt: string | null, prompt: string, attachments: Array<string>, model: string, policy: PermissionPolicySetting, 
/**
 * Redacted (`core::redact::redact`) — for the diagnostics bundle, not for replay.
 */
argv: Array<string>, 
/**
 * The parsed `ChatEvent` stream minus `TextDelta`/`ThinkingDelta`/
 * `ToolCallInputDelta` noise (`DATA-MODEL.md` §6). Stored as loose JSON rather than
 * typed `ChatEvent` so this record can round-trip through `Deserialize` without
 * widening `AppError`'s own derive surface just for archival storage.
 */
events: Array<JsonValue>, assistantText: string, toolCalls: Array<TurnToolCall>, result: TurnResultMeta | null, 
/**
 * The snapshot taken just before this turn ran (`core::snapshot`, `FR-SAFE-1`).
 * `#[serde(default)]` so a record a pre-M4 build wrote still loads.
 */
snapshotBefore: string | null, 
/**
 * Computed once, right after the turn, from `snapshotBefore` vs the working tree at
 * that moment (`FR-SAFE-2`) — an audit trail of what the turn did, independent of
 * `changes_for_turn`'s live recomputation (`SPEC.md` §8 open question 14).
 */
changes: Array<FileChange>, };

export type SessionIndexEntry = { id: string, startedAt: string, lastTurnAt: string, turnCount: number, totalCostUsd: number, title: string, };

export type SessionIndex = { schemaVersion: number, current: string | null, sessions: Array<SessionIndexEntry>, };

